const fs = require('fs');

const coursesStr = `
export const COURSES: Course[] = [
  // ==================== SEMESTER 1 (COMMON TO ALL MAJORS) ====================
  {
    code: 'MEC011',
    title: 'Engineering Drawing (1)',
    credits: 5,
    department: 'MEC',
    prerequisites: [],
    description: 'Introduction to engineering drawing, layout, lettering, dimensioning, geometric construction, projection, and sectional views.',
    level: 'Intro',
    category: 'Core Engineering',
    semesters: [1, 1, 1, 1, 1, 1],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'PHY111',
    title: 'Physics I',
    credits: 6,
    department: 'PHY',
    prerequisites: [],
    description: 'Classical mechanics, mechanics of particles, Newton laws, work-energy theorem, and rotational dynamics.',
    level: 'Intro',
    category: 'Core Engineering',
    semesters: [1, 1, 1, 1, 1, 1],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'MAT122',
    title: 'Statics',
    credits: 5,
    department: 'MAT',
    prerequisites: [],
    description: 'Forces, moments, couples, equilibrium of particles and rigid bodies, analysis of simple structures, trusses, friction, and centroids.',
    level: 'Intro',
    category: 'Core Engineering',
    semesters: [1, 1, 1, 1, 1, 1],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'MAT111',
    title: 'Mathematics I',
    credits: 5,
    department: 'MAT',
    prerequisites: [],
    description: 'Functions, limits, continuity, differentiation, integration, and applications in engineering problems.',
    level: 'Intro',
    category: 'Core Engineering',
    semesters: [1, 1, 1, 1, 1, 1],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'UC1',
    title: 'University Requirement (1)',
    credits: 3,
    department: 'UNI',
    prerequisites: [],
    description: 'University compulsory requirement course.',
    level: 'Intro',
    category: 'University Requirement',
    semesters: [1, 1, 1, 1, 1, 1],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'UC2',
    title: 'University Requirement (2)',
    credits: 3,
    department: 'UNI',
    prerequisites: [],
    description: 'University compulsory requirement course.',
    level: 'Intro',
    category: 'University Requirement',
    semesters: [1, 1, 1, 1, 1, 1],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'UC3',
    title: 'University Requirement (3)',
    credits: 3,
    department: 'UNI',
    prerequisites: [],
    description: 'University compulsory requirement course.',
    level: 'Intro',
    category: 'University Requirement',
    semesters: [1, 1, 1, 1, 1, 1],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },

  // ==================== SEMESTER 2 (COMMON TO ALL MAJORS) ====================
  {
    code: 'MEC012',
    title: 'Engineering Drawing (2)',
    credits: 5,
    department: 'MEC',
    prerequisites: ['MEC011'],
    description: 'Advanced projection, isometric drawing, assembly drawings, sectioning, and CAD software tools introduction.',
    level: 'Intro',
    category: 'Core Engineering',
    semesters: [2, 2, 2, 2, 2, 2],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'MEC041',
    title: 'Production Engineering',
    credits: 4,
    department: 'MEC',
    prerequisites: [],
    description: 'Overview of casting, welding, sheet metal work, machining processes, tools, and industrial manufacturing concepts.',
    level: 'Intro',
    category: 'Core Engineering',
    semesters: [2, 2, 2, 2, 2, 2],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'CHE142',
    title: 'Engineering Chemistry',
    credits: 5,
    department: 'CHE',
    prerequisites: [],
    description: 'Chemical thermodynamics, kinetics, electrochemistry, corrosion, polymers, fuels, and environmental chemical safety.',
    level: 'Intro',
    category: 'Core Engineering',
    semesters: [2, 2, 2, 2, 2, 2],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'MAT112',
    title: 'Mathematics II',
    credits: 4,
    department: 'MAT',
    prerequisites: [],
    description: 'Integration techniques, series, multivariable calculus, and introduction to differential equations.',
    level: 'Intro',
    category: 'Core Engineering',
    semesters: [2, 2, 2, 2, 2, 2],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'MAT121',
    title: 'Dynamics',
    credits: 4,
    department: 'MAT',
    prerequisites: [],
    description: 'Kinematics and kinetics of particles, planar systems, impulse-momentum methods, and rotational systems of equations.',
    level: 'Intro',
    category: 'Core Engineering',
    semesters: [2, 2, 2, 2, 2, 2],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'PHY211',
    title: 'Physics II',
    credits: 5,
    department: 'PHY',
    prerequisites: [],
    description: 'Electromagnetism, Coulomb\\'s law, electric potential, capacitance, current, magnetic fields, and electromagnetic induction.',
    level: 'Intro',
    category: 'Core Engineering',
    semesters: [2, 2, 2, 2, 2, 2],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },
  {
    code: 'UC4',
    title: 'University Requirement (4)',
    credits: 3,
    department: 'UNI',
    prerequisites: [],
    description: 'University compulsory requirement course.',
    level: 'Intro',
    category: 'University Requirement',
    semesters: [2, 2, 2, 2, 2, 2],
    majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering']
  },

  // ==================== SEMESTER 3 ====================
  { code: 'MEC111', title: 'Mechanical Engineering Drawing', credits: 6, department: 'MEC', prerequisites: ['MEC011'], description: '', level: 'Intermediate', category: 'Core Engineering', semesters: [3, 3, 3, 3], majors: ['Petrol and Gas Engineering', 'Aerospace Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'MEC151', title: 'Thermal Energy', credits: 5, department: 'MEC', prerequisites: [], description: '', level: 'Intermediate', category: 'Thermal Sciences', semesters: [3, 3, 3, 3, 3, 3], majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'PHY321', title: 'Solid State Physics', credits: 5, department: 'PHY', prerequisites: [], description: '', level: 'Intermediate', category: 'Physical Sciences', semesters: [3, 3, 3, 3, 3, 3], majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'MAT211', title: 'Mathematics III', credits: 6, department: 'MAT', prerequisites: [], description: '', level: 'Intermediate', category: 'Mathematics', semesters: [3, 3, 3, 3, 3, 3], majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'ELE112', title: 'Electronic Circuits', credits: 5, department: 'ELE', prerequisites: ['PHY211'], description: '', level: 'Intermediate', category: 'Electrical Engineering', semesters: [3, 3, 3, 3], majors: ['Petrol and Gas Engineering', 'Aerospace Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'UC5', title: 'University Requirement (5)', credits: 3, department: 'UNI', prerequisites: [], description: '', level: 'Intro', category: 'University Requirement', semesters: [10, 3, 3, 10, 3, 3], majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'PHY231', title: 'Modern Physics', credits: 6, department: 'PHY', prerequisites: ['PHY211'], description: '', level: 'Intermediate', category: 'Physical Sciences', semesters: [3], majors: ['Civil Engineering'] },
  { code: 'CIV113', title: 'Structural Analysis', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [3, 3], majors: ['Environmental Architecture', 'Civil Engineering'] },
  { code: 'CIV111', title: 'Structural Mechanics', credits: 6, department: 'CIV', prerequisites: ['MAT121'], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [3], majors: ['Civil Engineering'] },
  { code: 'ARC111', title: 'Visual Perception, Art & Design', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Intro', category: 'Environmental Architecture', semesters: [3], majors: ['Environmental Architecture'] },
  { code: 'ARC131', title: 'History & Theory of Ancient Architecture', credits: 4, department: 'ARC', prerequisites: [], description: '', level: 'Intro', category: 'Environmental Architecture', semesters: [3], majors: ['Environmental Architecture'] },
  { code: 'ARC141', title: 'Introduction to Building Systems', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Intro', category: 'Environmental Architecture', semesters: [3, 5], majors: ['Environmental Architecture', 'Civil Engineering'] },

  // ==================== SEMESTER 4 ====================
  { code: 'ELE111', title: 'Electrical Circuits', credits: 7, department: 'ELE', prerequisites: ['PHY211'], description: '', level: 'Intermediate', category: 'Electrical Engineering', semesters: [4, 4, 4], majors: ['Aerospace Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'MEC131', title: 'Metallurgy & Material Testing', credits: 6, department: 'MEC', prerequisites: ['PHY111'], description: '', level: 'Intermediate', category: 'Materials', semesters: [4, 4, 4, 4], majors: ['Petrol and Gas Engineering', 'Aerospace Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'ELE271', title: 'Electrical Machines', credits: 6, department: 'ELE', prerequisites: ['ELE112'], description: '', level: 'Intermediate', category: 'Electrical Engineering', semesters: [4, 4, 4], majors: ['Petrol and Gas Engineering', 'Aerospace Engineering', 'Mechatronics Engineering'] },
  { code: 'MAT313', title: 'Differential Equations & Numerical Analysis', credits: 7, department: 'MAT', prerequisites: [], description: '', level: 'Advanced', category: 'Mathematics', semesters: [4, 4, 4], majors: ['Aerospace Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'UC6', title: 'University Requirement (6)', credits: 3, department: 'UNI', prerequisites: [], description: '', level: 'Intro', category: 'University Requirement', semesters: [4, 4, 4, 4, 4, 4], majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'ELE113', title: 'Electrical Drawing', credits: 7, department: 'ELE', prerequisites: ['MEC012'], description: '', level: 'Intermediate', category: 'Electrical Engineering', semesters: [4], majors: ['Biomedical Engineering'] },
  { code: 'MEC252', title: 'Heat & Mass Transfer', credits: 5, department: 'MEC', prerequisites: ['MEC151'], description: '', level: 'Intermediate', category: 'Thermal Sciences', semesters: [4, 5, 5], majors: ['Petrol and Gas Engineering', 'Aerospace Engineering', 'Mechatronics Engineering'] },
  { code: 'MEC121', title: 'Manufacturing Technology', credits: 6, department: 'MEC', prerequisites: ['MEC041'], description: '', level: 'Intermediate', category: 'Manufacturing', semesters: [4, 5, 5, 5], majors: ['Petrol and Gas Engineering', 'Aerospace Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'MEC253', title: 'Thermodynamics', credits: 5, department: 'MEC', prerequisites: [], description: '', level: 'Intermediate', category: 'Thermal Sciences', semesters: [4, 5, 6, 5], majors: ['Petrol and Gas Engineering', 'Aerospace Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'CIV112', title: 'Strength of Materials', credits: 6, department: 'CIV', prerequisites: ['PHY111'], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [4, 4, 4], majors: ['Environmental Architecture', 'Civil Engineering', 'Petrol and Gas Engineering'] },
  { code: 'CIV114', title: 'Civil Engineering Drawing', credits: 6, department: 'CIV', prerequisites: ['MEC012'], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [4], majors: ['Civil Engineering'] },
  { code: 'CIV131', title: 'Surveying (1)', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [4, 4], majors: ['Environmental Architecture', 'Civil Engineering'] },
  { code: 'CIV211', title: 'Concrete Structures Design (1)', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [4, 5], majors: ['Civil Engineering', 'Environmental Architecture'] },
  { code: 'CIV212', title: 'Steel Structures Design (1)', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [4, 6], majors: ['Civil Engineering', 'Environmental Architecture'] },
  { code: 'ARC121', title: 'Architectural Studio 1', credits: 8, department: 'ARC', prerequisites: ['ARC111'], description: '', level: 'Intermediate', category: 'Environmental Architecture', semesters: [4], majors: ['Environmental Architecture'] },
  { code: 'ARC132', title: 'History & Theory of Medieval Architecture', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Intro', category: 'Environmental Architecture', semesters: [4], majors: ['Environmental Architecture'] },

  // ==================== SEMESTER 5 ====================
  { code: 'MEC212', title: 'Stress Analysis', credits: 6, department: 'MEC', prerequisites: ['MEC131'], description: '', level: 'Intermediate', category: 'Structural Mechanics', semesters: [5, 5, 5], majors: ['Mechatronics Engineering', 'Aerospace Engineering', 'Petrol and Gas Engineering'] },
  { code: 'MEC251', title: 'Fluid Mechanics', credits: 6, department: 'MEC', prerequisites: ['MAT112', 'MAT121'], description: '', level: 'Intermediate', category: 'Fluid Sciences', semesters: [5, 5, 5], majors: ['Mechatronics Engineering', 'Aerospace Engineering', 'Petrol and Gas Engineering'] },
  { code: 'MAT221', title: 'Rigid Body Dynamics', credits: 6, department: 'MAT', prerequisites: [], description: '', level: 'Intermediate', category: 'Dynamics', semesters: [5, 5], majors: ['Mechatronics Engineering', 'Aerospace Engineering'] },
  { code: 'MEC112', title: 'Machine Construction', credits: 6, department: 'MEC', prerequisites: ['MEC111'], description: '', level: 'Intermediate', category: 'Aerospace Engineering', semesters: [5], majors: ['Aerospace Engineering'] },
  { code: 'MEC341', title: 'Measurement & Instrumentation', credits: 4, department: 'MEC', prerequisites: ['ELE112'], description: '', level: 'Advanced', category: 'Controls', semesters: [5, 6], majors: ['Petrol and Gas Engineering', 'Mechatronics Engineering'] },
  { code: 'PGE231', title: 'Separation Processes', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Intermediate', category: 'Petrol & Gas Engineering', semesters: [5], majors: ['Petrol and Gas Engineering'] },
  { code: 'CHE111', title: 'Organic Chemistry', credits: 6, department: 'CHE', prerequisites: [], description: '', level: 'Intermediate', category: 'Chemistry', semesters: [5], majors: ['Petrol and Gas Engineering'] },
  { code: 'CHE232', title: 'Analytical Chemistry I', credits: 6, department: 'CHE', prerequisites: [], description: '', level: 'Intermediate', category: 'Chemistry', semesters: [5], majors: ['Petrol and Gas Engineering'] },
  { code: 'ARC222', title: 'Architectural Studio 2', credits: 8, department: 'ARC', prerequisites: ['ARC121'], description: '', level: 'Intermediate', category: 'Environmental Architecture', semesters: [5], majors: ['Environmental Architecture'] },
  { code: 'ARC233', title: 'History of Islamic Architecture', credits: 4, department: 'ARC', prerequisites: [], description: '', level: 'Intermediate', category: 'Environmental Architecture', semesters: [5], majors: ['Environmental Architecture'] },
  { code: 'ARC242', title: 'Sanitary Installations', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Intermediate', category: 'Environmental Architecture', semesters: [5], majors: ['Environmental Architecture'] },
  { code: 'ARC271', title: 'Introduction to Urban Design', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Intermediate', category: 'Environmental Architecture', semesters: [5], majors: ['Environmental Architecture'] },
  { code: 'CIV213', title: 'Concrete Technology (1)', credits: 6, department: 'CIV', prerequisites: ['CIV113'], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [5], majors: ['Civil Engineering'] },
  { code: 'CIV216', title: 'Computer Aided Structural Design', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [5], majors: ['Civil Engineering'] },
  { code: 'CIV221', title: 'Infrastructure Network Planning', credits: 6, department: 'CIV', prerequisites: ['CIV131'], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [5], majors: ['Civil Engineering'] },
  { code: 'CIV231', title: 'Surveying (2)', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [5], majors: ['Civil Engineering'] },
  { code: 'CIV232', title: 'Soil Mechanics (1)', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [5], majors: ['Civil Engineering'] },

  // ==================== SEMESTER 6 ====================
  { code: 'MEC211', title: 'Mechanics of Machines & Vibrations', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Intermediate', category: 'Mechatronics Engineering', semesters: [6, 6], majors: ['Mechatronics Engineering', 'Aerospace Engineering'] },
  { code: 'MEC213', title: 'Machine Elements Design', credits: 6, department: 'MEC', prerequisites: ['MEC112'], description: '', level: 'Intermediate', category: 'Mechatronics Engineering', semesters: [6, 6], majors: ['Mechatronics Engineering', 'Aerospace Engineering'] },
  { code: 'MEC271', title: 'Automatic Control', credits: 8, department: 'MEC', prerequisites: [], description: '', level: 'Intermediate', category: 'Controls', semesters: [6, 6], majors: ['Mechatronics Engineering', 'Aerospace Engineering'] },
  { code: 'MEC281', title: 'Aerospace Design & Simulation (1)', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Intermediate', category: 'Aerospace Engineering', semesters: [6], majors: ['Aerospace Engineering'] },
  { code: 'ELE211', title: 'Electromagnetic Fields', credits: 6, department: 'ELE', prerequisites: ['MAT112', 'PHY211'], description: '', level: 'Intermediate', category: 'Electrical Engineering', semesters: [6], majors: ['Biomedical Engineering'] },
  { code: 'ELE212', title: 'Electrical Measurements & Instruments', credits: 6, department: 'ELE', prerequisites: ['ELE112'], description: '', level: 'Intermediate', category: 'Electrical Engineering', semesters: [6], majors: ['Biomedical Engineering'] },
  { code: 'ELE331', title: 'Fundamentals of Communication Systems', credits: 6, department: 'ELE', prerequisites: [], description: '', level: 'Intermediate', category: 'Electrical Engineering', semesters: [6], majors: ['Biomedical Engineering'] },
  { code: 'BME211', title: 'Structure & Function of the Body', credits: 4, department: 'BME', prerequisites: [], description: '', level: 'Intermediate', category: 'Biomedical Engineering', semesters: [6], majors: ['Biomedical Engineering'] },
  { code: 'CSE014', title: 'Structured Programming', credits: 6, department: 'CSE', prerequisites: [], description: '', level: 'Intro', category: 'Core Engineering', semesters: [6, 7, 6], majors: ['Biomedical Engineering', 'Mechatronics Engineering', 'Petrol and Gas Engineering'] },
  { code: 'CIV214', title: 'Concrete Technology (2)', credits: 6, department: 'CIV', prerequisites: ['CIV211'], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [6], majors: ['Civil Engineering'] },
  { code: 'CIV215', title: 'Foundation Design (1)', credits: 6, department: 'CIV', prerequisites: ['CIV213'], description: '', level: 'Advanced', category: 'Civil Engineering', semesters: [6], majors: ['Civil Engineering'] },
  { code: 'CIV222', title: 'Fluid Mechanics for Civil Engineers', credits: 8, department: 'CIV', prerequisites: [], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [6], majors: ['Civil Engineering'] },
  { code: 'CIV261', title: 'Introduction to Transportation & Traffic Engineering', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [6], majors: ['Civil Engineering'] },
  { code: 'CIV271', title: 'Computer Applications in Geotechnical', credits: 6, department: 'CIV', prerequisites: ['CIV213'], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [6], majors: ['Civil Engineering'] },
  { code: 'ARC223', title: 'Architectural Studio 3', credits: 8, department: 'ARC', prerequisites: ['ARC222'], description: '', level: 'Intermediate', category: 'Environmental Architecture', semesters: [6], majors: ['Environmental Architecture'] },
  { code: 'ARC212', title: 'Interior Design & Modern Art', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Intermediate', category: 'Environmental Architecture', semesters: [6], majors: ['Environmental Architecture'] },
  { code: 'ARC234', title: 'Theory & Criticism of Modern & Contemporary', credits: 4, department: 'ARC', prerequisites: [], description: '', level: 'Intermediate', category: 'Environmental Architecture', semesters: [6], majors: ['Environmental Architecture'] },
  { code: 'ARC235', title: 'History & Theory of City Planning', credits: 4, department: 'ARC', prerequisites: [], description: '', level: 'Intermediate', category: 'Environmental Architecture', semesters: [6], majors: ['Environmental Architecture'] },
  { code: 'ARC373', title: 'Urban Planning', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [6], majors: ['Environmental Architecture'] },
  { code: 'MEC353', title: 'Thermal Power Engineering', credits: 4, department: 'MEC', prerequisites: ['MEC151'], description: '', level: 'Advanced', category: 'Thermal Sciences', semesters: [6], majors: ['Petrol and Gas Engineering'] },
  { code: 'MEC255', title: 'Energy Resources', credits: 4, department: 'MEC', prerequisites: ['MEC151'], description: '', level: 'Intermediate', category: 'Thermal Sciences', semesters: [6, 8, 9], majors: ['Petrol and Gas Engineering', 'Biomedical Engineering', 'Aerospace Engineering'] },
  { code: 'PGE212', title: 'Drilling Engineering - I', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Intermediate', category: 'Petrol & Gas Engineering', semesters: [6], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE232', title: 'Chemistry of Petrochemical Processes', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Intermediate', category: 'Petrol & Gas Engineering', semesters: [6], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE271', title: 'Applied Chemistry', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Intermediate', category: 'Chemistry', semesters: [6], majors: ['Petrol and Gas Engineering'] },

  // ==================== SEMESTER 7 ====================
  { code: 'MEC329', title: 'Industrial Robotics', credits: 6, department: 'MEC', prerequisites: ['MEC271'], description: '', level: 'Advanced', category: 'Mechatronics Engineering', semesters: [7], majors: ['Mechatronics Engineering'] },
  { code: 'MEC342', title: 'Additive Manufacturing 1', credits: 6, department: 'MEC', prerequisites: ['MEC121'], description: '', level: 'Advanced', category: 'Mechatronics Engineering', semesters: [7], majors: ['Mechatronics Engineering'] },
  { code: 'MEC321', title: 'DOE & Quality Control', credits: 6, department: 'MEC', prerequisites: ['MAT211'], description: '', level: 'Advanced', category: 'Aerospace Engineering', semesters: [7], majors: ['Aerospace Engineering'] },
  { code: 'MEC351', title: 'Flow Machines & Advanced Fluid Dynamics', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Engineering', semesters: [7], majors: ['Aerospace Engineering'] },
  { code: 'CSE272', title: 'Embedded Systems', credits: 6, department: 'CSE', prerequisites: [], description: '', level: 'Intermediate', category: 'Aerospace Engineering', semesters: [7], majors: ['Aerospace Engineering'] },
  { code: 'BME312', title: 'Biomedical Engineering Design', credits: 6, department: 'BME', prerequisites: ['BME211'], description: '', level: 'Advanced', category: 'Biomedical Engineering', semesters: [7], majors: ['Biomedical Engineering'] },
  { code: 'BME313', title: 'Introduction to Bio Engineering', credits: 4, department: 'BME', prerequisites: ['BME211'], description: '', level: 'Advanced', category: 'Biomedical Engineering', semesters: [7], majors: ['Biomedical Engineering'] },
  { code: 'BME321', title: 'Magnetic Resonance Imaging', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Engineering', semesters: [7], majors: ['Biomedical Engineering'] },
  { code: 'BME213', title: 'Biochemistry', credits: 4, department: 'BME', prerequisites: [], description: '', level: 'Intermediate', category: 'Biomedical Engineering', semesters: [7], majors: ['Biomedical Engineering'] },
  { code: 'CIV312', title: 'Concrete Structures Design (2)', credits: 6, department: 'CIV', prerequisites: ['CIV113'], description: '', level: 'Advanced', category: 'Civil Engineering', semesters: [7], majors: ['Civil Engineering'] },
  { code: 'CIV325', title: 'Applied Hydrology', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Engineering', semesters: [7], majors: ['Civil Engineering'] },
  { code: 'CIV341', title: 'Cost Estimation & Project Control', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Engineering', semesters: [7], majors: ['Civil Engineering'] },
  { code: 'CIV371', title: 'Project Management', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Engineering', semesters: [7], majors: ['Civil Engineering'] },
  { code: 'ARC325', title: 'Environmental Design Studio 1', credits: 8, department: 'ARC', prerequisites: ['ARC223'], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [7], majors: ['Environmental Architecture'] },
  { code: 'ARC335', title: '20th Century Egyptian Architecture & Art', credits: 4, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [7], majors: ['Environmental Architecture'] },
  { code: 'ARC343', title: 'Working Drawing Studio 1', credits: 8, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [7], majors: ['Environmental Architecture'] },
  { code: 'ARC355', title: 'Illumination & Ventilation in Buildings', credits: 4, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [7], majors: ['Environmental Architecture'] },
  { code: 'MEC355', title: 'Combustion', credits: 6, department: 'MEC', prerequisites: ['MEC353'], description: '', level: 'Advanced', category: 'Thermal Sciences', semesters: [7], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE221', title: 'Applied Thermodynamics', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Intermediate', category: 'Petrol & Gas Engineering', semesters: [7], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE371', title: 'Environmental Chemistry', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Chemistry', semesters: [7], majors: ['Petrol and Gas Engineering'] },
  { code: 'UE1', title: 'Elective University (1)', credits: 4, department: 'UNI', prerequisites: [], description: '', level: 'Intro', category: 'University Elective', semesters: [7, 7, 7, 7, 7, 7], majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'UE2', title: 'Elective University (2)', credits: 4, department: 'UNI', prerequisites: [], description: '', level: 'Intro', category: 'University Elective', semesters: [8, 8, 8, 8, 7, 7], majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },

  // ==================== SEMESTER 8 ====================
  { code: 'MEC361', title: 'Mechanical System Design', credits: 6, department: 'MEC', prerequisites: ['MEC213'], description: '', level: 'Advanced', category: 'Mechatronics Engineering', semesters: [8], majors: ['Mechatronics Engineering'] },
  { code: 'ELE384', title: 'Power Electronics & Motor Drives', credits: 6, department: 'ELE', prerequisites: ['ELE112'], description: '', level: 'Advanced', category: 'Electrical Engineering', semesters: [8], majors: ['Mechatronics Engineering'] },
  { code: 'MEC372', title: 'Sensors & Measurement Systems', credits: 4, department: 'MEC', prerequisites: ['MEC341'], description: '', level: 'Advanced', category: 'Mechatronics Engineering', semesters: [8], majors: ['Mechatronics Engineering'] },
  { code: 'MEC375', title: 'Advanced Automatic Control', credits: 6, department: 'MEC', prerequisites: ['MEC271'], description: '', level: 'Advanced', category: 'Controls', semesters: [8], majors: ['Mechatronics Engineering'] },
  { code: 'MEC472', title: 'Mechatronic Systems Design', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Engineering', semesters: [8], majors: ['Mechatronics Engineering'] },
  { code: 'MEC262', title: 'Aerodynamics of Vehicles', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Intermediate', category: 'Aerospace Engineering', semesters: [8], majors: ['Aerospace Engineering'] },
  { code: 'MEC343', title: 'Finite Element Method', credits: 6, department: 'MEC', prerequisites: ['MAT211'], description: '', level: 'Advanced', category: 'Aerospace Engineering', semesters: [8, 8], majors: ['Aerospace Engineering', 'Civil Engineering'] },
  { code: 'MEC345', title: 'Aeroplanes Mechatronics', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Engineering', semesters: [8], majors: ['Aerospace Engineering'] },
  { code: 'MEC383', title: 'Air Engines', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Engineering', semesters: [8], majors: ['Aerospace Engineering'] },
  { code: 'MEC384', title: 'Aeroplanes Engines Design Using CAD', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Engineering', semesters: [8], majors: ['Aerospace Engineering'] },
  { code: 'ELE312', title: 'Analog Circuits', credits: 8, department: 'ELE', prerequisites: ['ELE112'], description: '', level: 'Advanced', category: 'Electrical Engineering', semesters: [8], majors: ['Biomedical Engineering'] },
  { code: 'BME322', title: 'System Psychology & Biomechanics', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Engineering', semesters: [8], majors: ['Biomedical Engineering'] },
  { code: 'BME315', title: 'Biomedical Systems Analysis', credits: 6, department: 'BME', prerequisites: ['BME312'], description: '', level: 'Advanced', category: 'Biomedical Engineering', semesters: [8], majors: ['Biomedical Engineering'] },
  { code: 'BME323', title: 'Modern Optical Microscopy & Imaging', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Engineering', semesters: [8], majors: ['Biomedical Engineering'] },
  { code: 'ARC326', title: 'Environmental Design Studio 2', credits: 8, department: 'ARC', prerequisites: ['ARC325'], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [8], majors: ['Environmental Architecture'] },
  { code: 'ARC344', title: 'Working Drawing Studio 2', credits: 8, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [8], majors: ['Environmental Architecture'] },
  { code: 'CIV217', title: 'Finite Element Method', credits: 6, department: 'CIV', prerequisites: ['MAT211'], description: '', level: 'Intermediate', category: 'Civil Engineering', semesters: [8], majors: ['Civil Engineering'] },
  { code: 'CIV313', title: 'Steel Structures Design (2)', credits: 6, department: 'CIV', prerequisites: ['CIV113'], description: '', level: 'Advanced', category: 'Civil Engineering', semesters: [8], majors: ['Civil Engineering'] },
  { code: 'CIV462', title: 'Legal & Contracts Issues in Construction Projects', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Engineering', semesters: [8], majors: ['Civil Engineering'] },
  { code: 'PGE355', title: 'Environment & Safety Management', credits: 2, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Engineering', semesters: [8], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE213', title: 'Petroleum Geology & Geophysical Exploration', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Intermediate', category: 'Petrol & Gas Engineering', semesters: [8], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE311', title: 'Petro-physics', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Engineering', semesters: [8], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE312', title: 'Properties of Reservoir Fluids', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Engineering', semesters: [8], majors: ['Petrol and Gas Engineering'] },

  // ==================== SEMESTER 9 ====================
  { code: 'MEC471', title: 'Microcontroller & Embedded Systems', credits: 6, department: 'MEC', prerequisites: ['ELE111'], description: '', level: 'Advanced', category: 'Mechatronics Engineering', semesters: [9], majors: ['Mechatronics Engineering'] },
  { code: 'MEC445', title: 'Design of Autonomous Systems', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Engineering', semesters: [9], majors: ['Mechatronics Engineering'] },
  { code: 'ELE322', title: 'Advanced Semiconductor Devices', credits: 4, department: 'ELE', prerequisites: [], description: '', level: 'Advanced', category: 'Electrical Engineering', semesters: [9], majors: ['Biomedical Engineering'] },
  { code: 'MEC491', title: 'Graduation Project 1', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Engineering', semesters: [9, 9], majors: ['Mechatronics Engineering', 'Aerospace Engineering'] },
  { code: 'ARC427', title: 'Environmental Design & Technology Studio', credits: 8, department: 'ARC', prerequisites: ['ARC343'], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [9], majors: ['Environmental Architecture'] },
  { code: 'ARC474', title: 'Housing', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [9], majors: ['Environmental Architecture'] },
  { code: 'ARC491', title: 'Graduation Project 1', credits: 8, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [9], majors: ['Environmental Architecture'] },
  { code: 'ARC458', title: 'Feasibility Studies & Project Management', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [9], majors: ['Environmental Architecture'] },
  { code: 'MEC231', title: 'Engineering Economy', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Intermediate', category: 'Core Engineering', semesters: [9], majors: ['Civil Engineering'] },
  { code: 'CIV491', title: 'Graduation Project 1', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Engineering', semesters: [9], majors: ['Civil Engineering'] },
  { code: 'PGE491', title: 'Graduation Project 1', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Engineering', semesters: [9], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE313', title: 'Drilling Engineering II', credits: 6, department: 'PGE', prerequisites: ['PGE212'], description: '', level: 'Advanced', category: 'Petrol & Gas Engineering', semesters: [9], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE314', title: 'Well Logging', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Engineering', semesters: [9], majors: ['Petrol and Gas Engineering'] },

  // ==================== SEMESTER 10 ====================
  { code: 'MEC492', title: 'Graduation Project 2', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Engineering', semesters: [10, 10], majors: ['Mechatronics Engineering', 'Aerospace Engineering'] },
  { code: 'BME492', title: 'Graduation Project 2', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Engineering', semesters: [10], majors: ['Biomedical Engineering'] },
  { code: 'ARC492', title: 'Graduation Project 2', credits: 8, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture', semesters: [10], majors: ['Environmental Architecture'] },
  { code: 'CIV492', title: 'Graduation Project 2', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Engineering', semesters: [10], majors: ['Civil Engineering'] },
  { code: 'PGE492', title: 'Graduation Project 2', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Engineering', semesters: [10], majors: ['Petrol and Gas Engineering'] },
  { code: 'UC7', title: 'University Requirement (7)', credits: 4, department: 'UNI', prerequisites: [], description: '', level: 'Intro', category: 'University Requirement', semesters: [10, 10, 10, 10, 10, 10], majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },
  { code: 'UE3', title: 'Elective University (3)', credits: 4, department: 'UNI', prerequisites: [], description: '', level: 'Intro', category: 'University Elective', semesters: [10, 10, 10, 10, 10, 10], majors: ['Petrol and Gas Engineering', 'Environmental Architecture', 'Aerospace Engineering', 'Civil Engineering', 'Mechatronics Engineering', 'Biomedical Engineering'] },

  // ==================== INDUSTRIAL PROJECTS ====================
  { code: 'MEC391', title: 'Industrial Project', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Engineering', semesters: [8, 8], majors: ['Mechatronics Engineering', 'Aerospace Engineering'] },
  { code: 'BME391', title: 'Industrial Project', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Engineering', semesters: [8], majors: ['Biomedical Engineering'] },
  { code: 'CIV391', title: 'Field Project', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Engineering', semesters: [8], majors: ['Civil Engineering'] },
  { code: 'PGE391', title: 'Industrial Project', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Engineering', semesters: [8], majors: ['Petrol and Gas Engineering'] },

  // ==================== ELECTIVES ====================
  { code: 'MEC235', title: 'Nanotechnology basics', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [7], majors: ['Mechatronics Engineering'] },
  { code: 'MEC242', title: 'CNC Machine', credits: 6, department: 'MEC', prerequisites: ['MEC121'], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [7], majors: ['Mechatronics Engineering'] },
  { code: 'MEC273', title: 'Hydraulics & Pneumatics Control', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [7], majors: ['Mechatronics Engineering'] },
  { code: 'MEC363', title: 'System Psychology & Biomechanics', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [9], majors: ['Mechatronics Engineering'] },
  { code: 'MEC381', title: 'Gait Analysis & Locomotion', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [9], majors: ['Mechatronics Engineering'] },
  { code: 'MEC428', title: 'Industrial Communication & Network Systems', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [10], majors: ['Mechatronics Engineering'] },
  { code: 'MEC429', title: 'Industrial automated assembly mechanisms', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [10], majors: ['Mechatronics Engineering'] },
  { code: 'MEC441', title: 'Computer Integrated Manufacturing', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [10], majors: ['Mechatronics Engineering'] },
  { code: 'MEC474', title: 'Modeling & Simulation of Mechatronics systems', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [10], majors: ['Mechatronics Engineering'] },
  { code: 'MEC482', title: 'Rehabilitation of Robots', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [10], majors: ['Mechatronics Engineering'] },
  { code: 'ELE432', title: 'Digital Signal Processing', credits: 6, department: 'ELE', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [10], majors: ['Mechatronics Engineering'] },
  { code: 'ELE433', title: 'Biomedical Engineering', credits: 6, department: 'ELE', prerequisites: [], description: '', level: 'Advanced', category: 'Mechatronics Elective', semesters: [10], majors: ['Mechatronics Engineering'] },
  // biomed electives
  { code: 'BME224', title: 'Introduction to Medical Imaging', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Elective', semesters: [7], majors: ['Biomedical Engineering'] },
  { code: 'BME333', title: 'Microbiology & Immunity', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Elective', semesters: [7], majors: ['Biomedical Engineering'] },
  { code: 'BME222', title: 'Biomechanics 2: Biological Tissues', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Elective', semesters: [9], majors: ['Biomedical Engineering'] },
  { code: 'BME311', title: 'Biomedical Sensors', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Elective', semesters: [9], majors: ['Biomedical Engineering'] },
  { code: 'BME324', title: 'Intermediate Fluid mechanics', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Elective', semesters: [10], majors: ['Biomedical Engineering'] },
  { code: 'BME421', title: 'Bio Regenerative Engineering', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Elective', semesters: [10], majors: ['Biomedical Engineering'] },
  { code: 'BME422', title: 'Regenerative Engineering Applications', credits: 6, department: 'BME', prerequisites: [], description: '', level: 'Advanced', category: 'Biomedical Elective', semesters: [10], majors: ['Biomedical Engineering'] },
  // aerospace electives
  { code: 'MEC435', title: 'Heat Treatment', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Elective', semesters: [7], majors: ['Aerospace Engineering'] },
  { code: 'MEC282', title: 'Airplanes Fuel Systems', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Elective', semesters: [9], majors: ['Aerospace Engineering'] },
  { code: 'MEC382', title: 'Aerospace Maintenance Engineering', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Elective', semesters: [9], majors: ['Aerospace Engineering'] },
  { code: 'MEC481', title: 'Vehicle Design & Simulation (2)', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Aerospace Elective', semesters: [10], majors: ['Aerospace Engineering'] },
  { code: 'MEC490', title: 'Modern Vehicles Technologies', credits: 6, department: 'MEC', prerequisites: ['MEC351'], description: '', level: 'Advanced', category: 'Aerospace Elective', semesters: [10], majors: ['Aerospace Engineering'] },
  { code: 'MEC436', title: 'Decision Analysis', credits: 6, department: 'MEC', prerequisites: ['MEC321'], description: '', level: 'Advanced', category: 'Aerospace Elective', semesters: [10], majors: ['Aerospace Engineering'] },
  // civil electives
  { code: 'MEC336', title: 'Human Factors in System Design', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Elective', semesters: [7], majors: ['Civil Engineering'] },
  { code: 'MEC337', title: 'Social Network Behavior Models', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Elective', semesters: [7], majors: ['Civil Engineering'] },
  { code: 'MEC232', title: 'Production Systems', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Elective', semesters: [8], majors: ['Civil Engineering'] },
  { code: 'MEC331', title: 'Metrology & Measuring Instruments', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Elective', semesters: [9], majors: ['Civil Engineering'] },
  { code: 'MEC411', title: 'Non-Destructive Testing (1)', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Elective', semesters: [9], majors: ['Civil Engineering'] },
  { code: 'CIV321', title: 'Insulation Works', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Elective', semesters: [10], majors: ['Civil Engineering'] },
  { code: 'CIV461', title: 'Risk & Safety Management', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Elective', semesters: [10], majors: ['Civil Engineering'] },
  { code: 'CIV482', title: 'Dynamic Floor Vibrations', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Elective', semesters: [10], majors: ['Civil Engineering'] },
  { code: 'CIV314', title: 'Behavior of Steel Structures', credits: 6, department: 'CIV', prerequisites: [], description: '', level: 'Advanced', category: 'Civil Elective', semesters: [10], majors: ['Civil Engineering'] },
  // petrol electives
  { code: 'PGE354', title: 'Chemical Products Design & Development', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [7], majors: ['Petrol and Gas Engineering'] },
  { code: 'MEC493', title: 'Vehicle Safety Systems', credits: 6, department: 'MEC', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [7], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE331', title: 'Petroleum Production Engineering', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [7], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE433', title: 'Petroleum Economics', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [9], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE434', title: 'Project Planning & Management', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [9], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE435', title: 'Instrumentation & Process Control', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [10], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE431', title: 'Well Testing', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [10], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE332', title: 'Natural Gas Engineering', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [10], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE315', title: 'Reservoir Engineering', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [10], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE422', title: 'Petroleum Refinery Engineering', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [10], majors: ['Petrol and Gas Engineering'] },
  { code: 'PGE432', title: 'Reservoir Simulation', credits: 6, department: 'PGE', prerequisites: [], description: '', level: 'Advanced', category: 'Petrol & Gas Elective', semesters: [10], majors: ['Petrol and Gas Engineering'] },
  // architecture electives
  { code: 'ARC336', title: 'Architecture, Culture & Heritage', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [7], majors: ['Environmental Architecture'] },
  { code: 'ARC437', title: 'Documentation of Heritage Buildings', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [7], majors: ['Environmental Architecture'] },
  { code: 'ARC438', title: 'Heritage Management', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [7], majors: ['Environmental Architecture'] },
  { code: 'ARC439', title: 'Restoration of Heritage Buildings', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [7], majors: ['Environmental Architecture'] },
  { code: 'ARC375', title: 'Community Development', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [8], majors: ['Environmental Architecture'] },
  { code: 'ARC476', title: 'Sustainable Urbanism', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [8], majors: ['Environmental Architecture'] },
  { code: 'ARC478', title: 'Sustainable Landscape', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [8], majors: ['Environmental Architecture'] },
  { code: 'ARC477', title: 'Urban Sociology', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [10], majors: ['Environmental Architecture'] },
  { code: 'ARC356', title: 'Architectural Acoustics', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [10], majors: ['Environmental Architecture'] },
  { code: 'ARC382', title: 'Building Economics', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [10], majors: ['Environmental Architecture'] },
  { code: 'ARC483', title: 'Real Estate Marketing', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [10], majors: ['Environmental Architecture'] },
  { code: 'ARC484', title: 'Advanced Building Systems', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [10], majors: ['Environmental Architecture'] },
  { code: 'ARC485', title: 'Applications of GIS', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [10], majors: ['Environmental Architecture'] },
  { code: 'ARC381', title: 'Professional Practice & Legislations', credits: 6, department: 'ARC', prerequisites: [], description: '', level: 'Advanced', category: 'Environmental Architecture Elective', semesters: [10], majors: ['Environmental Architecture'] }
];

export const MAJORS = [
  'Petrol and Gas Engineering',
  'Environmental Architecture',
  'Aerospace Engineering',
  'Civil Engineering',
  'Mechatronics Engineering',
  'Biomedical Engineering'
];
\`;

let srcData = fs.readFileSync('./src/data.ts', 'utf8');

// replace COURSES and MAJORS block
const startIndex = srcData.indexOf('export const COURSES: Course[] = [');
const getFullCohortStudentsIndex = srcData.indexOf('export function getFullCohortStudents(): Student[] {');

const newData = srcData.substring(0, startIndex) + coursesStr + '\\n\\n' + srcData.substring(getFullCohortStudentsIndex);

fs.writeFileSync('./src/data.ts', newData, 'utf8');
